M48
; DRILL file {KiCad 9.0.4} date 2025-10-16T00:16:20-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-16T00:16:20-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X112.481Y-62.459
X142.921Y-62.596
T2
X118.145Y-71.25
X139.57Y-71.5
M30
